adding rule option added

diff --git a/PenShi b/PenShi
--- a/PenShi
+++ b/PenShi
@@ -1,6 +1,8 @@
 #!/bin/bash
-commands="commands.txt"
+
+filename="commands"
 iptables_rules_backup_dir="backup" 
+
 #Functions 
 iptablesWithSudo(){
     sudo iptables "$@"
@@ -12,6 +14,7 @@ usage() {
     -rules		rules managent
     "
     echo "Options :
+    --a     add rules (all rules must be in commands file)
     --l		list all rules
     --f		delete all rules 
     --d 	delete one rule by chain (FORWARD , INPUT ,OUTPUT) and id (get it from $0  -rules --l)
@@ -78,7 +81,19 @@ restore_iptables_rules() {
 
 rules() {
   
-    if [[ "$1" == "--l" ]]; then
+    if [[ "$1" == "--a" ]]; then
+
+    if [[ ! -f $filename ]]; then
+        echo "File not found!"
+        exit 1
+    fi
+
+    while IFS= read -r line; do
+        echo "Executing: $line"
+        sudo $line
+    done < "$filename"
+
+    elif [[ "$1" == "--l" ]]; then
         echo "Listing rules"
         sleep 2
         iptablesWithSudo -L --line-numbers
